# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('price', models.IntegerField(max_length=200)),
                ('num_in_stock', models.IntegerField(max_length=200)),
            ],
        ),
    ]
