# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_stock',
            field=models.IntegerField(default=20, max_length=200),
            preserve_default=False,
        ),
    ]
